# Generated by Django 5.2.5 on 2025-08-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenit', '0002_url_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='category',
            field=models.CharField(blank=True, choices=[('work', 'Work'), ('socials', 'Socials'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='url',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.SlugField(help_text='Customize the slug portion of your link', unique=True),
        ),
    ]
